#################################
#################################
## Action for Test Compilation ##
#################################
#################################
name: Test Compilation

# Allow to call this workflow by other workflows
on:
  workflow_call:

# Set the Jobs
jobs:
  ##################
  # Test Converter #
  ##################
  test_converter:
    # Name the Job
    name: Converter test
    # Set the agent to run on
    runs-on: ubuntu-latest

    # Load all steps
    steps:
      # Checkout the code base
      - name: Checkout repo content
        uses: actions/checkout@v6
      # Setup python
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      # Install dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      # Run test script
      - name: Run test script
        run: "pytest tests/"
      - name : Show Files
        run : "ls -R"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shared-dtx-files
          path: tests/test_case_*/results/testcase*.dtx
          retention-days: 1

  ###############
  # Compile dtx #
  ###############
  build_latex:
    # Name the Job
    name: Compile PDF
    # Set the agent to run on
    runs-on: ubuntu-latest
    # Requires
    needs: test_converter

    permissions:
      contents: write
      actions: read

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Set up git repository
        uses: actions/checkout@v6
      - name: Download artifacts (dtx files)
        uses: actions/download-artifact@v4
        with:
          name: shared-dtx-files
          path: tests/
      ####################
      # Run the compiler #
      ####################
      - name: Show Files
        run: "ls -R"
      - name: Compile LaTeX document (test case 1)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: "testcase1.dtx"
          glob_root_file: true
          working_directory: tests/test_case_1/results
      - name: Compile LaTeX document (test case 2)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: "testcase2.dtx"
          glob_root_file: true
          working_directory: tests/test_case_2/results
      - name: Compile LaTeX document (test case 3)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: "testcase3.dtx"
          glob_root_file: true
          working_directory: tests/test_case_3/results
      - name: Show Files
        run: "ls -R"
      ###################
      # Push dtx commit #
      ###################
      - name: Auto commit created LaTeX files
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Automated commit: Add created files during test compilation"
          file_pattern: '*.dtx *.pdf *.ins *.sty *.txt'
